# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
# 当前分支，adm64为稳定，~amd64为最新
ACCEPT_KEYWORDS="~amd64"
# 为所语言设置编译标志
#COMMON_FLAGS="-march=native -O3 -pipe"
COMMON_FLAGS="-mtune=skylake -march=skylake -O3 -pipe"
# 为两个变量使用相同的设置
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"


# 优化Rust CPU编译
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native"
export CARGO_BUILD_JOBS=3


# 如果未定义，Portage 的默认行为是：
# - 将 MAKEOPTS jobs 值设置为与 'nproc' 返回的相同线程数
# - 将 MAKEOPTS load-average 值设置为略高于 'nproc' 返回的线程数，因为它是一个阻尼值
# 请根据系统需要替换 '4' （使用系统线程数或GB记内存除以二的最小值），或者不设置。
# -j = distcc+local/2
MAKEOPTS="-j 4 -l 5"

# 调试日志
#DISTCC_VERBOSE=1


FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

# NOTE: This stage was built with the bindist USE flag enabled

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8

GENTOO_MIRRORS="https://mirrors.tuna.tsinghua.edu.cn/gentoo"

# 设置软件许可证
ACCEPT_LICENSE="* -@EULA"

# 签名？
USE="modules-sign"
# Optionally, to use custom signing keys.
MODULES_SIGN_KEY="/path/to/kernel_key.pem"
MODULES_SIGN_CERT="/path/to/kernel_key.pem" # Only required if the MODULES_SIGN_KEY does not also contain the certificate.
MODULES_SIGN_HASH="sha512" # Defaults to sha512.

# 使用自定义内核
#USE="dist-kernel"

GIT_CEILING_DIRECTORIES="/"
